#端口
server:
  port: 8081


#springboot的配置
mysql:
  username: sctbc
  password: sctbc
  url: jdbc:mysql://101.37.253.142:3306/sctbc


#springboot数据源的配置 上面mysql暂时没有使用
spring:
  datasource:
    url: jdbc:mysql://101.37.253.142:3306/sctbc?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    password: sctbc
    username: sctbc
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500


  #文件上传功能 开启
  servlet:
    multipart:
      enabled: true
      #文件总大小
      max-request-size: 10MB
      #单个文件最大值
      max-file-size: 10MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss


#mybatis的文件配置
mybatis:
  mapper-locations: classpath:mapping/*Mapping.xml
  type-aliases-package: com.sctbc.pojo
#  config-location: classpath:mybatis-config.xml


